POST http://localhost:3000/excel/try



###
POST http://localhost:3000/transactions/load-file
Content-Type: multipart/form-data; boundary=your-boundary

--your-boundary
Content-Disposition: form-data; name="file"; filename="transactions.xlsx"
Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet

< transactions.xlsx
--your-boundary--

###
GET http://localhost:3000/excel/get_by_userID?userId=N0rQ3GHjlmMEfKHUPmTUn2Tv3Y72



###
POST  http://localhost:3000/transactions/add-bill
content-type: application/json

{
  "token": "eyJhbGciOiJSUzI1NiIsImtpZCI6ImRmOGIxNTFiY2Q5MGQ1YjMwMjBlNTNhMzYyZTRiMzA3NTYzMzdhNjEiLCJ0eXAiOiJKV1QifQ.eyJyb2xlIjoiYWRtaW4iLCJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vdGF4bXlzZWxmLTVkOGEwIiwiYXVkIjoidGF4bXlzZWxmLTVkOGEwIiwiYXV0aF90aW1lIjoxNzE4NDg2MTcwLCJ1c2VyX2lkIjoiTDVnSmtyZFFaNWdHbXRlNVh4UmdhZ2txcE9MMiIsInN1YiI6Ikw1Z0prcmRRWjVnR210ZTVYeFJnYWdrcXBPTDIiLCJpYXQiOjE3MTg0ODYxNzAsImV4cCI6MTcxODQ4OTc3MCwiZW1haWwiOiJoYXJlbGF6YXJAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsiaGFyZWxhemFyQGdtYWlsLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.VrtD9TrA4XCnLfDqouFxMSJanF3wiuwizzWyK53BFt1GO2cFkdaFYYfk1hDQ8ySgaYA5-NQaYaVtZwmUaoXamxxc_3CX3QYTwWYqBsWzd4QpBZSNPnNUsVcl73gkN_63XYR8Lzxxf_y91qEDVD5O3UG5VHNkBLgmFZVbTZMhGHrqvqq2S2bgt8bBiCKXmoSD_a1v5KZqSHV54r8YU7NfIDMTPaH4mflPr7jR8F5KScnOYCGM8Mrs_nlOfK3lmNFGwh5BUeNfE7QE3chDdAoHtn0r7zgEwvboFjTI6w_ijEcHdEjrblKY4YgM6YaIX6PsGrWcDS9JTnE1nyzOfL1wpw",
  "billName": "demo_bill"
}

###
POST  http://localhost:3000/transactions/7/sources
content-type: application/json

{
  "token": "eyJhbGciOiJSUzI1NiIsImtpZCI6ImRmOGIxNTFiY2Q5MGQ1YjMwMjBlNTNhMzYyZTRiMzA3NTYzMzdhNjEiLCJ0eXAiOiJKV1QifQ.eyJyb2xlIjoiYWRtaW4iLCJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vdGF4bXlzZWxmLTVkOGEwIiwiYXVkIjoidGF4bXlzZWxmLTVkOGEwIiwiYXV0aF90aW1lIjoxNzE4Mzc1MzEzLCJ1c2VyX2lkIjoiTDVnSmtyZFFaNWdHbXRlNVh4UmdhZ2txcE9MMiIsInN1YiI6Ikw1Z0prcmRRWjVnR210ZTVYeFJnYWdrcXBPTDIiLCJpYXQiOjE3MTgzNzUzMTMsImV4cCI6MTcxODM3ODkxMywiZW1haWwiOiJoYXJlbGF6YXJAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsiaGFyZWxhemFyQGdtYWlsLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.IlDkaCB96qjCsQQVXFGB5LizdjB_zlBVXZwT2JESa1IRr7zZMH1R20XmWzcenSdAjrG6MxnlCzP63K5S0_wzgt4ItLi-bZnl3LDB-Vh3uWa9UhXJdCcdk0BG_DV_LN1Ww3PkeuZFlANh-GXu3jRqddnthGJYopqIELpMGwVm8XsjcPf12Cmvsk_H4TaQcHaozaqwNF-ZJaQBB_HeHADCC2BfIjkLmB-BtHPNWzohUOw7PNiLdn1cD4la8U4-RpzUnG5ngq2f7GKZx87ikIwM6u9Czctn0q-aBXNRgU3ilHrT6L6pUFj9yAbXonMe1EdITe8oV_QI6Sq09T1PeS_6sw",
  "sourceName": "5670"
}


###
GET  http://localhost:3000/transactions/7/get-transactions
content-type: application/json

{
  "token": "eyJhbGciOiJSUzI1NiIsImtpZCI6Ijc5M2Y3N2Q0N2ViOTBiZjRiYTA5YjBiNWFkYzk2ODRlZTg1NzJlZTYiLCJ0eXAiOiJKV1QifQ.eyJyb2xlIjoiYWRtaW4iLCJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vdGF4bXlzZWxmLTVkOGEwIiwiYXVkIjoidGF4bXlzZWxmLTVkOGEwIiwiYXV0aF90aW1lIjoxNzE5NTEzOTgwLCJ1c2VyX2lkIjoiTDVnSmtyZFFaNWdHbXRlNVh4UmdhZ2txcE9MMiIsInN1YiI6Ikw1Z0prcmRRWjVnR210ZTVYeFJnYWdrcXBPTDIiLCJpYXQiOjE3MTk1MTM5ODAsImV4cCI6MTcxOTUxNzU4MCwiZW1haWwiOiJoYXJlbGF6YXJAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsiaGFyZWxhemFyQGdtYWlsLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.Av-UY50oIB4nLcyfSMnPuHfyaUTPwxAd2RcSGCdPQ9AsmRKuCzW9MzkBwSl2VqHkcnhzyICDukzQoC2Jg-FNLuwwGXbcdakV_Bc9jpKrM_x-SNIF4yOoAWz3baC8prVuZ9v4SzLUmFPpY3cKP4lsGpqbME0abH7sFNQooBYGvUZPtXzVX2sjhNruhju5WYv7YpVmYo2P0gtcK-ea-vtkc0IcFDijNUxJN2bcInsClVRLkiyr6lvBFn0zzGXaTzrehQsip8-Wyvm07MvMHIFw_Mb3MzdWloCrVtTroNWhuweMV-y1Wil4ZTn3NEdo49sctrsynAy88_bALDFaUqNfRw"
}



###
GET  http://localhost:3000/transactions/get-incomes?billId=1
content-type: application/json

{
  "token": "eyJhbGciOiJSUzI1NiIsImtpZCI6Ijc5M2Y3N2Q0N2ViOTBiZjRiYTA5YjBiNWFkYzk2ODRlZTg1NzJlZTYiLCJ0eXAiOiJKV1QifQ.eyJyb2xlIjoiYWRtaW4iLCJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vdGF4bXlzZWxmLTVkOGEwIiwiYXVkIjoidGF4bXlzZWxmLTVkOGEwIiwiYXV0aF90aW1lIjoxNzE5NTE4MDE2LCJ1c2VyX2lkIjoiTDVnSmtyZFFaNWdHbXRlNVh4UmdhZ2txcE9MMiIsInN1YiI6Ikw1Z0prcmRRWjVnR210ZTVYeFJnYWdrcXBPTDIiLCJpYXQiOjE3MTk1MTgwMTYsImV4cCI6MTcxOTUyMTYxNiwiZW1haWwiOiJoYXJlbGF6YXJAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsiaGFyZWxhemFyQGdtYWlsLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.LjK3Y9BWWbNarHMj0Hr3xojpztCfh2S0-gro_jD-q0sP7xgZkOmaIMkQjbmCIsnJHjUoxajIcOazif2NRXfXVrHxL-m21dqxIrFrJlqDdTQDXP9soo2TbLd24ncBHh68nuI78YfbKqSxT3W8sFPi4tPsze08guWHXfZ93e0e5UMFTE7udsD4Tdq5s0vCGXml8IkwuGfEgvakb32U7Ogva1tNo34lAB2ITc2DWt8OZ0p0RZMLz_NBmtHFUbvR_DMkgjD1p7aM0ph7DpvpyauTlYYqPwiZMLpNiZ0zYT---iRiyZLGbmKLx75xvK7tZx-cOnTQP8DPnnMjeLE4oNsGhw"
}


