import { SelfEmployedGuideComponent } from './self-employed-guide.component';
import { SELF_EMPLOYED_GUIDE_SLIDES } from './self-employed-guide.content';

describe('SelfEmployedGuideComponent', () => {
  let component: SelfEmployedGuideComponent;
  beforeEach(() => component = new SelfEmployedGuideComponent());
  it('orders the main sequence and ends with the product slides', () => {
    expect(component.slides[5].title).toBe('מי יכול להיות פטור, ומי זעיר?');
    expect(component.slides[4].title).toBe('החובות של כל עסק');
    expect(component.slides[4].items?.every(item => item.description.includes('ביטוח לאומי'))).toBeTrue();
    expect(component.slides[2].title).toBe('כשאתם שכירים, המעסיק מטפל בהכל');
    expect(component.slides.map(s => s.id)).toEqual(['cover', 'basic-concepts', 'employee-payroll', 'business-types', 'income-tax-overview', 'status-comparison', 'micro-blockers', 'tax-authorities', 'learning-summary', 'exempt-documents', 'authorized-documents', 'study-fund', 'study-comparison', 'pension', 'pension-tax-benefits', 'expense-principle', 'expense-depreciation', 'expense-savings', 'product-pain', 'product-solution']);
    component.previousSlide();
    expect(component.currentSlideIndex).toBe(0);
    for (let i = 0; i < 20; i++) component.nextSlide();
    expect(component.currentSlideIndex).toBe(19);
    expect(component.isLastMainSlide).toBeTrue();
  });
  for (const chapter of ['income', 'vat', 'ni'] as const) {
    it(`bounds ${chapter} navigation and returns after its last slide`, () => {
      component.openChapter(chapter);
      component.previousSlide();
      expect(component.currentSlideIndex).toBe(0);
      expect(component.currentSlide.id).toBe(component.chapterIds[chapter][0]);
      const count = component.slides.length;
      for (let i = 1; i < count; i++) component.nextSlide();
      expect(component.progressPercent).toBe(100);
      expect(component.isLastMainSlide).toBeFalse();
      component.nextSlide();
      expect(component.activeChapter).toBeNull();
      expect(component.currentSlide.id).toBe('tax-authorities');
      expect(component.currentSlideIndex).toBe(7);
    });
    it(`returns from every ${chapter} slide and restarts on reentry`, () => {
      for (const id of component.chapterIds[chapter]) {
        component.goToSlide(id);
        expect(component.activeChapter).toBe(chapter);
        component.returnToAuthorities();
        expect(component.currentSlideIndex).toBe(7);
        component.openChapter(chapter);
        expect(component.currentSlideIndex).toBe(0);
      }
    });
  }
  it('assigns all 31 slides exactly once and opens income at combined income', () => {
    const ids = [...component.mainIds, ...Object.values(component.chapterIds).flat()];
    expect(new Set(ids).size).toBe(31);
    expect([...ids].sort()).toEqual(SELF_EMPLOYED_GUIDE_SLIDES.map(s => s.id).sort());
    component.openChapter('income');
    expect(component.currentSlide.id).toBe('income-combination');
    component.nextSlide();
    component.previousSlide();
    expect(component.currentSlide.title).toBe('שכיר וגם עצמאי? בסוף שנה הכל נפגש');
  });
  it('shows the income calculator only at the end and returns to the hub', () => {
    component.openChapter('income');
    expect(component.slides.filter(slide => slide.layout === 'tax-simulator').length).toBe(1);
    expect(component.slides[1].id).toBe('advances-introduction');
    expect(component.slides.length).toBe(5);
    expect(component.slides[2].id).toBe('advances-calculation');
    expect(component.slides[2].artworkAlt).toContain('אפשר לבקש עדכון מקדמות');
    expect(component.slides[3].id).toBe('advances-payment');
    expect(component.slides[3].artworkAlt).toContain('שתי הערות בתחתית');
    expect(component.slides[3].artworkAlt).toContain('בעל עסק זעיר במסלול המקוצר');
    for (let i = 1; i < component.slides.length; i++) component.nextSlide();
    expect(component.currentSlide.id).toBe('tax-simulator');
    component.previousSlide();
    expect(component.currentSlide.id).toBe('advances-payment');
    component.nextSlide();
    component.nextSlide();
    expect(component.currentSlide.id).toBe('tax-authorities');
  });
  it('explains insurance rates immediately before its calculator', () => {
    component.openChapter('ni');
    expect(component.slides.map(s => s.id)).toEqual(['ni-status', 'ni-payment', 'ni-rates', 'ni-calculator']);
    component.goToSlide('ni-rates');
    component.nextSlide();
    expect(component.currentSlide.id).toBe('ni-calculator');
    component.previousSlide();
    expect(component.currentSlide.id).toBe('ni-rates');
  });
  it('continues from the authorities to both product artworks and back', () => {
    component.returnToAuthorities();
    expect(component.isLastMainSlide).toBeFalse();
    component.nextSlide();
    expect(component.currentSlide.id).toBe('learning-summary');
    expect(component.currentSlide.artwork).toContain('learning-summary-approved.png');
    component.nextSlide();
    expect(component.currentSlide.id).toBe('exempt-documents');
    expect(component.currentSlide.artwork).toContain('exempt-documents-approved.png');
    component.nextSlide();
    expect(component.currentSlide.id).toBe('authorized-documents');
    expect(component.currentSlide.artwork).toContain('authorized-documents-approved.png');
    component.nextSlide();
    expect(component.currentSlide.id).toBe('study-fund');
    expect(component.currentSlide.artwork).toContain('study-fund-approved.png');
    component.nextSlide();
    expect(component.currentSlide.id).toBe('study-comparison');
    component.nextSlide();
    expect(component.currentSlide.id).toBe('pension');
    expect(component.currentSlide.artwork).toContain('pension-approved.png');
    component.nextSlide();
    expect(component.currentSlide.id).toBe('pension-tax-benefits');
    expect(component.currentSlide.artwork).toContain('pension-tax-benefits-approved.png');
    component.nextSlide();
    expect(component.currentSlide.id).toBe('expense-principle');
    component.nextSlide();
    expect(component.currentSlide.id).toBe('expense-depreciation');
    expect(component.currentSlide.artwork).toContain('expense-depreciation-approved.png');
    component.nextSlide();
    expect(component.currentSlide.id).toBe('expense-savings');
    component.nextSlide();
    expect(component.currentSlide.id).toBe('product-pain');
    expect(component.currentSlide.artwork).toContain('product-pain-approved.png');
    component.nextSlide();
    expect(component.currentSlide.id).toBe('product-solution');
    expect(component.currentSlide.artwork).toContain('product-solution-approved.png');
    expect(component.isLastMainSlide).toBeTrue();
    component.previousSlide();
    component.previousSlide();
    expect(component.currentSlide.id).toBe('expense-savings');
    component.previousSlide();
    expect(component.currentSlide.id).toBe('expense-depreciation');
    component.previousSlide();
    component.previousSlide();
    expect(component.currentSlide.id).toBe('pension-tax-benefits');
    component.previousSlide();
    expect(component.currentSlide.id).toBe('pension');
    component.previousSlide();
    expect(component.currentSlide.id).toBe('study-comparison');
    component.previousSlide();
    expect(component.currentSlide.id).toBe('study-fund');
    component.previousSlide();
    expect(component.currentSlide.id).toBe('authorized-documents');
    component.previousSlide();
    expect(component.currentSlide.id).toBe('exempt-documents');
    component.previousSlide();
    expect(component.currentSlide.id).toBe('learning-summary');
    component.previousSlide();
    expect(component.currentSlide.id).toBe('tax-authorities');
  });
  it('ignores invalid targets and respects RTL keys and inputs', () => {
    component.goToSlide(undefined);
    component.goToSlide('unknown');
    expect(component.currentSlideIndex).toBe(0);
    component.onKeydown(new KeyboardEvent('keydown', { key: 'ArrowLeft' }));
    expect(component.currentSlideIndex).toBe(1);
    component.onKeydown(new KeyboardEvent('keydown', { key: 'ArrowRight' }));
    expect(component.currentSlideIndex).toBe(0);
    const event = new KeyboardEvent('keydown', { key: 'ArrowLeft', cancelable: true });
    Object.defineProperty(event, 'target', { value: document.createElement('input') });
    component.onKeydown(event);
    expect(component.currentSlideIndex).toBe(0);
    expect(event.defaultPrevented).toBeFalse();
  });
  it('returns on Escape inside a chapter without closing the guide', () => {
    spyOn(component.closeGuide, 'emit');
    component.openChapter('vat');
    component.onKeydown(new KeyboardEvent('keydown', { key: 'Escape' }));
    expect(component.currentSlide.id).toBe('tax-authorities');
    expect(component.closeGuide.emit).not.toHaveBeenCalled();
  });
});
