/**
 * Reads back the Phase 3 backfill result from keepintax_prodcopy (after
 * 2026-07-13_phase3_backfill.ts MODE=apply) and emits literal UPDATE
 * statements for cutover.sql Section 6 — same precedent as
 * 2026-07-12_generate-catalog-migration-sql.ts: bake in the EXACT values
 * this session's resolution produced, rather than have cutover.sql re-run
 * the resolution live against production's catalog state at cutover time
 * (which could in principle have drifted from this dump).
 *
 *   DB_DATABASE=keepintax_prodcopy NODE_ENV=production SKIP_BOOT_SEED=true \
 *     npx ts-node -r tsconfig-paths/register scripts/migrations/2026-07-13_generate-phase3-sql.ts
 */
import { NestFactory } from '@nestjs/core';
import { DataSource } from 'typeorm';
import * as fs from 'fs';
import * as path from 'path';
import { AppModule } from '../../src/app.module';

const OUT = path.resolve(__dirname, '2026-07-13_phase3_data.sql');

function sqlVal(v: any): string {
  if (v === null || v === undefined) return 'NULL';
  if (typeof v === 'number') return String(v);
  return `'${String(v).replace(/\\/g, '\\\\').replace(/'/g, "''")}'`;
}

async function main() {
  if (!process.env.DB_DATABASE || process.env.DB_DATABASE !== 'keepintax_prodcopy') {
    throw new Error(`Refusing to run against DB_DATABASE=${process.env.DB_DATABASE}`);
  }
  const app = await NestFactory.createApplicationContext(AppModule, { logger: ['warn', 'error'] });
  const dataSource = app.get(DataSource);

  const lines: string[] = [];
  lines.push('-- Generated by backend/scripts/migrations/2026-07-13_generate-phase3-sql.ts');
  lines.push(`-- against keepintax_prodcopy, ${new Date().toISOString()}`);
  lines.push('');

  // ── expense ──
  const expenses = await dataSource.query(
    `SELECT id, subCategoryId, sectionIdSnapshot, sectionCodeSnapshot, sectionNameSnapshot, accountIdSnapshot, accountCodeSnapshot, accountNameSnapshot, code6111Snapshot, description, approvalStatus FROM expense ORDER BY id`,
  );
  lines.push(`-- expense (${expenses.length} rows)`);
  for (const e of expenses) {
    lines.push(
      `UPDATE \`expense\` SET subCategoryId=${sqlVal(e.subCategoryId)}, sectionIdSnapshot=${sqlVal(e.sectionIdSnapshot)}, sectionCodeSnapshot=${sqlVal(e.sectionCodeSnapshot)}, sectionNameSnapshot=${sqlVal(e.sectionNameSnapshot)}, accountIdSnapshot=${sqlVal(e.accountIdSnapshot)}, accountCodeSnapshot=${sqlVal(e.accountCodeSnapshot)}, accountNameSnapshot=${sqlVal(e.accountNameSnapshot)}, code6111Snapshot=${sqlVal(e.code6111Snapshot)}, description=${sqlVal(e.description)}, approvalStatus=${sqlVal(e.approvalStatus)} WHERE id=${e.id};`,
    );
  }
  lines.push('');

  // ── journal_entry.description backfills (only rows this session actually touched) ──
  const journalDescriptions = await dataSource.query(
    `SELECT je.id, je.description FROM journal_entry je INNER JOIN expense e ON e.journalEntryNumber = je.entryNumber AND e.businessNumber = je.issuerBusinessNumber WHERE je.referenceType = 'EXPENSE'`,
  );
  lines.push(`-- journal_entry.description (${journalDescriptions.length} EXPENSE-referenced rows — re-asserted idempotently; only rows that were NULL/empty actually changed this session)`);
  for (const j of journalDescriptions) {
    lines.push(`UPDATE \`journal_entry\` SET description=${sqlVal(j.description)} WHERE id=${j.id} AND (description IS NULL OR description = '');`);
  }
  lines.push('');

  // ── supplier ──
  const suppliers = await dataSource.query(`SELECT id, subCategoryId FROM supplier WHERE subCategoryId IS NOT NULL ORDER BY id`);
  lines.push(`-- supplier (${suppliers.length} rows with a resolved subCategoryId)`);
  for (const s of suppliers) {
    lines.push(`UPDATE \`supplier\` SET subCategoryId=${sqlVal(s.subCategoryId)} WHERE id=${s.id};`);
  }
  lines.push('');

  // ── classified_transactions ──
  const rules = await dataSource.query(`SELECT id, subCategoryId FROM classified_transactions WHERE subCategoryId IS NOT NULL ORDER BY id`);
  lines.push(`-- classified_transactions (${rules.length} rows with a resolved subCategoryId)`);
  for (const r of rules) {
    lines.push(`UPDATE \`classified_transactions\` SET subCategoryId=${sqlVal(r.subCategoryId)} WHERE id=${r.id};`);
  }
  lines.push('');

  // ── extracted_document ──
  const docs = await dataSource.query(`SELECT id, sub_category_id as subCategoryId, document_kind as documentKind FROM extracted_document ORDER BY id`);
  lines.push(`-- extracted_document (${docs.length} rows)`);
  for (const d of docs) {
    lines.push(`UPDATE \`extracted_document\` SET sub_category_id=${sqlVal(d.subCategoryId)}, document_kind=${sqlVal(d.documentKind)} WHERE id=${d.id};`);
  }
  lines.push('');

  fs.writeFileSync(OUT, lines.join('\n') + '\n');
  console.log(`[generate-phase3-sql] wrote ${OUT} (${lines.length} lines)`);

  await app.close();
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
