export enum RegisterFormControls {
    
        FIRSTNAME = "fName",
        LASTNAME = "lName",
        ID = "id",
        GENDER = "gender",
        EMAIL = "email",
        PHONE = "phone",
        DATEOFBIRTH = "dateOfBirth",
        HAVECHILD = "haveCild",
        EMPLOYEMENTSTATUS = "employmentStatus",
        CITY = "city",
        FAMILYSTATUS = "familyStatus",
        PASSWORD = "password",
        // CHILDREN = "children",
        CHILD_FIRST_NAME = "childFName",
        CHILD_LAST_NAME = "childLName",
        CHILD_ID = "childID",
        CHILD_DATE_OF_BIRTH = "childDate",
        CONFIRM_PASSWORD = "confirmPassword",
        SPOUSEFIRSTNAME = "spouseFName",
        SPOUSELASTNAME = "spouseLName",
        SPOUSEID = "spouseId",
        SPOUSEPHONE = "spousePhone",
        SPOUSEEMAIL = "spouseEmail",
        SPOUSEDATEOFBIRTH = "spouseDateOfBirth",
        SPOUSEEMPLOYEMENTSTATUS = "spouseEmploymentStatus",
        SPOUSEGENDER = "spouseGender",
        BUSINESSTYPE = "businessType",
        BUSINESSFIELD = "businessField",
        BUSINESSNAME = "businessName",
        BUSINESSNUMBER = "businessNumber",
        BUSINESSDATE = "businessDate",
        BUSINESSINVENTORY = "businessInventory",
        SPOUSEBUSINESSTYPE = "spouseBusinessType",
        SPOUSEBUSINESSFIELD = "spouseBusinessField",
        SPOUSEBUSINESSNAME = "spouseBusinessName",
        SPOUSEBUSINESSNUMBER = "spouseBusinessNumber",
        SPOUSEBUSINESSDATE = "spouseBusinessDate",
        SPOUSEBUSINESSINVENTORY = "spouseBusinessInventory",

}

export enum RegisterFormModules {
    PERSONAL = 'personal',
    SPOUSE = 'spouse',
    CHILDREN = 'children',
    BUSINESS = 'business',
    VALIDATION = 'validation'
}