### Upload and immediately parse the file
POST http://localhost:3000/reports/upload-and-debug
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="INI.TXT"
Content-Type: text/plain

< C:\Users\harel\Downloads\INI.TXT
--WebAppBoundary--