export enum SubscriptionStatus {
  TRIAL = 'TRIAL',
  TRIAL_EXPIRED = 'TRIAL_EXPIRED',
  ACTIVE = 'ACTIVE',
  PAST_DUE = 'PAST_DUE',
  CANCELED = 'CANCELED',
}

export enum CheckoutSessionStatus {
  PENDING = 'PENDING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  EXPIRED = 'EXPIRED',
}

export enum WebhookLogStatus {
  RECEIVED = 'RECEIVED',
  PROCESSED = 'PROCESSED',
  FAILED = 'FAILED',
  IGNORED = 'IGNORED',
}

export enum BillingEventType {
  CHECKOUT_CREATED = 'CHECKOUT_CREATED',
  WEBHOOK_RECEIVED = 'WEBHOOK_RECEIVED',
  PAYMENT_VERIFIED = 'PAYMENT_VERIFIED',
  PAYMENT_SUCCESS = 'PAYMENT_SUCCESS',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  SUBSCRIPTION_ACTIVATED = 'SUBSCRIPTION_ACTIVATED',
  SUBSCRIPTION_CANCELED = 'SUBSCRIPTION_CANCELED',
  RENEWAL_SUCCESS = 'RENEWAL_SUCCESS',
  RENEWAL_FAILED = 'RENEWAL_FAILED',
  RETRY_SCHEDULED = 'RETRY_SCHEDULED',
  PLAN_CHANGE_REQUESTED = 'PLAN_CHANGE_REQUESTED',
  PLAN_CHANGED = 'PLAN_CHANGED',
  COUPON_REDEEMED = 'COUPON_REDEEMED',
  PROMOTION_APPLIED = 'PROMOTION_APPLIED',
  DISCOUNT_APPLIED = 'DISCOUNT_APPLIED',
}

/** Shared across Promotion, Coupon, and SubscriptionDiscount. */
export enum DiscountType {
  PERCENT = 'PERCENT',
  FIXED_AMOUNT = 'FIXED_AMOUNT',
  FIXED_PRICE = 'FIXED_PRICE',
}

/** Shared across Promotion, Coupon, and SubscriptionDiscount. */
export enum DurationType {
  ONCE = 'ONCE',
  REPEATING = 'REPEATING',
  FOREVER = 'FOREVER',
}

export enum CancellationReason {
  TOO_EXPENSIVE = 'TOO_EXPENSIVE',
  MISSING_FEATURE = 'MISSING_FEATURE',
  NOT_USING_ENOUGH = 'NOT_USING_ENOUGH',
  FOUND_ALTERNATIVE = 'FOUND_ALTERNATIVE',
  TECHNICAL_ISSUES = 'TECHNICAL_ISSUES',
  OTHER = 'OTHER',
}

export enum PlanChangeType {
  UPGRADE = 'UPGRADE',
  DOWNGRADE = 'DOWNGRADE',
}

export enum PlanChangeStatus {
  PENDING = 'PENDING',
  APPLIED = 'APPLIED',
  CANCELED = 'CANCELED',
  FAILED = 'FAILED',
}
