### 
# Create new bubuItem
POST http://localhost:3000/bubuItems
Content-Type: application/json

{
    "name": "Item1",
    "price": 23,
    "nickname": "Nick1"
}

###
# Create new bubuItem2
POST http://localhost:3000/bubuItems
Content-Type: application/json

{
    "name": "Item2",
    "price": 25,
    "nickname": "Nick2"
}

### 
# Get all bubuItems
GET http://localhost:3000/bubuItems

### 
# Get specific bubuItem (Replace :id with actual id generated during creation)
GET http://localhost:3000/bubuItems/3

### 
# Get all users
GET http://localhost:3000/users

### 
# Get specific user (Replace :id with actual id generated during creation)
GET http://localhost:3000/users/1


### 
# signup new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "firstName": "asdew",
    "lastName": "fas",
    "password": "12345",
    "email": "haps@pasu"
}

### 
# login user
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "password": "shisma7",
    "email": "hapsu@pasu"
}