
POST http://localhost:3000/expenses/try

###
POST http://localhost:3000/expenses/add-expense
content-type: application/json

{
  "token": "eyJhbGciOiJSUzI1NiIsImtpZCI6ImFlYzU4NjcwNGNhOTZiZDcwMzZiMmYwZDI4MGY5NDlmM2E5NzZkMzgiLCJ0eXAiOiJKV1QifQ.eyJyb2xlIjoiYWRtaW4iLCJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vdGF4bXlzZWxmLTVkOGEwIiwiYXVkIjoidGF4bXlzZWxmLTVkOGEwIiwiYXV0aF90aW1lIjoxNzA4MDA3NjAzLCJ1c2VyX2lkIjoiTDVnSmtyZFFaNWdHbXRlNVh4UmdhZ2txcE9MMiIsInN1YiI6Ikw1Z0prcmRRWjVnR210ZTVYeFJnYWdrcXBPTDIiLCJpYXQiOjE3MDgwMDc2MDMsImV4cCI6MTcwODAxMTIwMywiZW1haWwiOiJoYXJlbGF6YXJAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbImhhcmVsYXphckBnbWFpbC5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.JUPmVWbcrI3nDL_1P7t5Nwq7MCnWWrdomJ9zGjEfYHYmjk8KqIEFqjKL1u6aXhzlWAuOPwpIH6rE2T1qlVs6iNzSyRmyynWeJHvZEYgG1L8Wlx0VSxBH2_z-p1cqmc9kNXIMVK0FiEU7HrkxzstD99LIggUJoxiCPSNrz1GBuXvRZQ4IT43laYdB2sYCdqmnKXgL1Mym1-pycwBnfYtcvTYY7p57ZEMvZDr4kwYPKYwj4mazClRD910qdNBcSC_gWQhd-CMDk73yS7dxtHjuelGRIFKJGp1hz56LUSrivQhMVDaxf3lUPzSP8Oj3iUQLLATqmYf3ccKibxkst4zoMg",
  "supplier": "הוצאות דלק",
  "supplierId": "239458",
  "expenseNumber": "324234",
  "category": "רכב",
  "subCategory": "דלק",
  "sum": 850,
  "taxPercent": 25,
  "vatPercent": 45,
  "date": "2023-08-25T10:00:00Z",
  "isEquipment": false
}

###
POST https://taxmys16elf-prod-tau7bgxb3q-zf.a.run.app/expenses/add-expense
content-type: application/json

{
  "token": "eyJhbGciOiJSUzI1NiIsImtpZCI6ImFlYzU4NjcwNGNhOTZiZDcwMzZiMmYwZDI4MGY5NDlmM2E5NzZkMzgiLCJ0eXAiOiJKV1QifQ.eyJyb2xlIjoiYWRtaW4iLCJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vdGF4bXlzZWxmLTVkOGEwIiwiYXVkIjoidGF4bXlzZWxmLTVkOGEwIiwiYXV0aF90aW1lIjoxNzA4MDA3NjAzLCJ1c2VyX2lkIjoiTDVnSmtyZFFaNWdHbXRlNVh4UmdhZ2txcE9MMiIsInN1YiI6Ikw1Z0prcmRRWjVnR210ZTVYeFJnYWdrcXBPTDIiLCJpYXQiOjE3MDgwMDc2MDMsImV4cCI6MTcwODAxMTIwMywiZW1haWwiOiJoYXJlbGF6YXJAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbImhhcmVsYXphckBnbWFpbC5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.JUPmVWbcrI3nDL_1P7t5Nwq7MCnWWrdomJ9zGjEfYHYmjk8KqIEFqjKL1u6aXhzlWAuOPwpIH6rE2T1qlVs6iNzSyRmyynWeJHvZEYgG1L8Wlx0VSxBH2_z-p1cqmc9kNXIMVK0FiEU7HrkxzstD99LIggUJoxiCPSNrz1GBuXvRZQ4IT43laYdB2sYCdqmnKXgL1Mym1-pycwBnfYtcvTYY7p57ZEMvZDr4kwYPKYwj4mazClRD910qdNBcSC_gWQhd-CMDk73yS7dxtHjuelGRIFKJGp1hz56LUSrivQhMVDaxf3lUPzSP8Oj3iUQLLATqmYf3ccKibxkst4zoMg",
  "supplier": "הוצאות דלק",
  "supplierId": "239458",
  "expenseNumber": "324234",
  "category": "רכב",
  "subCategory": "דלק",
  "sum": 850,
  "taxPercent": 25,
  "vatPercent": 45,
  "date": "2023-08-25T10:00:00Z",
  "isEquipment": false
}


###
PATCH http://localhost:3000/expenses/update-expense/90
content-type: application/json

{
  "token": "eyJhbGciOiJSUzI1NiIsImtpZCI6ImFlYzU4NjcwNGNhOTZiZDcwMzZiMmYwZDI4MGY5NDlmM2E5NzZkMzgiLCJ0eXAiOiJKV1QifQ.eyJyb2xlIjoiYWRtaW4iLCJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vdGF4bXlzZWxmLTVkOGEwIiwiYXVkIjoidGF4bXlzZWxmLTVkOGEwIiwiYXV0aF90aW1lIjoxNzA4MDA3NjAzLCJ1c2VyX2lkIjoiTDVnSmtyZFFaNWdHbXRlNVh4UmdhZ2txcE9MMiIsInN1YiI6Ikw1Z0prcmRRWjVnR210ZTVYeFJnYWdrcXBPTDIiLCJpYXQiOjE3MDgwMDc2MDMsImV4cCI6MTcwODAxMTIwMywiZW1haWwiOiJoYXJlbGF6YXJAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbImhhcmVsYXphckBnbWFpbC5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.JUPmVWbcrI3nDL_1P7t5Nwq7MCnWWrdomJ9zGjEfYHYmjk8KqIEFqjKL1u6aXhzlWAuOPwpIH6rE2T1qlVs6iNzSyRmyynWeJHvZEYgG1L8Wlx0VSxBH2_z-p1cqmc9kNXIMVK0FiEU7HrkxzstD99LIggUJoxiCPSNrz1GBuXvRZQ4IT43laYdB2sYCdqmnKXgL1Mym1-pycwBnfYtcvTYY7p57ZEMvZDr4kwYPKYwj4mazClRD910qdNBcSC_gWQhd-CMDk73yS7dxtHjuelGRIFKJGp1hz56LUSrivQhMVDaxf3lUPzSP8Oj3iUQLLATqmYf3ccKibxkst4zoMg",
  "supplier": "הוצאות דלק",
  "supplierId": "239458",
  "expenseNumber": "33333",
  "category": "רכב",
  "subCategory": "דלק",
  "sum": 500,
  "taxPercent": 25,
  "vatPercent": 25,
  "date": "2023-08-25T10:00:00Z",
  "isEquipment": false
}

###
GET http://localhost:3000/expenses/search?userId=1&startDate=2022-01-01&endDate=2022-12-31&supplier=SomeSupplier&category=SomeCategory

###
GET http://localhost:3000/expenses/search


###
POST http://localhost:3000/expenses/add-default-category
content-type: application/json

{
  "token": "eyJhbGciOiJSUzI1NiIsImtpZCI6IjUzZWFiMDBhNzc5MTk3Yzc0MWQ2NjJmY2EzODE1OGJkN2JlNGEyY2MiLCJ0eXAiOiJKV1QifQ.eyJyb2xlIjoiYWRtaW4iLCJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vdGF4bXlzZWxmLTVkOGEwIiwiYXVkIjoidGF4bXlzZWxmLTVkOGEwIiwiYXV0aF90aW1lIjoxNzA3MTAyNjQ1LCJ1c2VyX2lkIjoiTDVnSmtyZFFaNWdHbXRlNVh4UmdhZ2txcE9MMiIsInN1YiI6Ikw1Z0prcmRRWjVnR210ZTVYeFJnYWdrcXBPTDIiLCJpYXQiOjE3MDcxMDI2NDUsImV4cCI6MTcwNzEwNjI0NSwiZW1haWwiOiJoYXJlbGF6YXJAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbImhhcmVsYXphckBnbWFpbC5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.QFdXD00QQY5a3TrT3GrM6xGDR5Am7J74cYOwMhEehnq0VPyws3rwHty_tcJLpBuRZK5PyVGQv2X-WrY7s4SrnglhTtBDRhsrw8xU2ZAMVbrpMyJSUmeT1_mKclAGYImwP9sE0uUGVQmEbzK849iuARObYyYHa3C6qFZ7oVY4hYn4oQgwCRtYYcGlsGpeF5_K3nyketPhvYg21LIc16UyU7PLiNR1wQory2ykLvdZdvIlxBVfmGk4ZLx1JFLzYahxssIzD-ELrsd1Iw7v1CoBG1Cm5gV1BQNmMdOwpL1hLI1nnnxNYKOYE1kgBmIs5aKtesV7JkYGPxZuly9UZnHjrQ",
  "category": "בנקים",
  "subCategory": "עמלות",
  "taxPercent": 25,
  "vatPercent": 25,
  "isEquipment": false
}


###
POST http://localhost:3000/expenses/add-user-category
content-type: application/json

{
  "token": "eyJhbGciOiJSUzI1NiIsImtpZCI6Ijc5M2Y3N2Q0N2ViOTBiZjRiYTA5YjBiNWFkYzk2ODRlZTg1NzJlZTYiLCJ0eXAiOiJKV1QifQ.eyJyb2xlIjoiYWRtaW4iLCJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vdGF4bXlzZWxmLTVkOGEwIiwiYXVkIjoidGF4bXlzZWxmLTVkOGEwIiwiYXV0aF90aW1lIjoxNzE5Nzc0MDIwLCJ1c2VyX2lkIjoiTDVnSmtyZFFaNWdHbXRlNVh4UmdhZ2txcE9MMiIsInN1YiI6Ikw1Z0prcmRRWjVnR210ZTVYeFJnYWdrcXBPTDIiLCJpYXQiOjE3MTk3NzQwMjAsImV4cCI6MTcxOTc3NzYyMCwiZW1haWwiOiJoYXJlbGF6YXJAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsiaGFyZWxhemFyQGdtYWlsLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.C6PV95xhGzkm8o3jkQorMtTF3HHsK3h9DhJ6JMm_6jZ7JP-MENlEH0mxfU3fg7efsHCrKpgiVp2JxJrEo6s9gdFLN9PLsbCmz_eX7Dph6BK2D4SxmWW6R0As0XshQs0x41aXwUg2ohYsD2gxKYAoAxbheeWatz1G5Ip0TD3oc9ptlydOyBgb6DsLe-GkDSrPQyxtjb8GSxYbBEbjZ0YK619xoL2zKJF17VoHmQMMCM72BsDhKZBesr6zvyTeL6L7wHsfh87fFWRKTUX1E5dgQ2WyZXAhFAKK89H8ubZSimbU3F9rcGKOquXxwYya-SDL3vvGKkaycZoHg4v1Atf7rA",
  "category": "רכב",
  "subCategory": "דלק",
  "taxPercent": 25,
  "vatPercent": 25,
  "reductionPercent": 0,
  "isEquipment": false,
  "isRecognized": false
}




### Get categories
GET http://localhost:3000/expenses/get-categories-list?isEquipment=true


### Get sub categories
GET http://localhost:3000/expenses/get-sub-categories-list?category=ציוד אלקטרוני&isEquipment=true


### Get default and user categories
GET http://localhost:3000/expenses/get-user-categories?isEquipment=true&isRecognized=true









###
POST  http://localhost:3000/expenses/add_supplier
content-type: application/json

{
  "name": "sdfsf",
  "category": "sdfasdg",
  "taxPercent": 25,
  "vatPercent": 45
}


### Get supplier
GET http://localhost:3000/expenses/get_supplier?name=sdfsf&userId=yh1ovqmsP2O6gAdYtMlBbw


### Get expenses by supplier
GET http://localhost:3000/expenses/get_by_supplier?supplier=Fox

### Get expenses by userID
GET http://localhost:3000/expenses/get_by_userID?userID=g5ShQuCNS8hldigE7YQTO8Sv3ml1



### Get expenses within date range
GET http://localhost:3000/expenses/get_by_date?startDate=2023-08-01&endDate=2023-08-31


GET http://localhost:3000/expenses?userId=8&price=450&tax_percent=25


### Get an estimate for an existing vehicle
#GET http://localhost:3000/reports?make=toyota&model=corolla&lng=0&lat=0&mileage=20000&year=1980

### Delete a user with a given ID
DELETE http://localhost:3000/expenses/1


###
POST http://localhost:3000/expenses/add-user-category
Content-Type: application/json
Authorization: Bearer <klsjdflaj>

{
  "categoryName": "Utilities",
  "subCategoryName": "Electricity",
  "taxPercent": 10,
  "vatPercent": 17,
  "reductionPercent": 5,
  "isEquipment": false,
  "isRecognized": true
}



### Test Case 1: Get all categories for a specific category
GET http://localhost:3000/expenses/get-categories?isDefault=null

### Test Case 1: Get all sub-categories for a specific category
GET http://localhost:3000/expenses/get-sub-categories?categoryId=2
