###
GET  http://localhost:3000/documents/get-setting-doc-by-type/1
content-type: application/json

###
PATCH   http://localhost:3000/documents/update-setting-doc-by-type/1
content-type: application/json

{
        "initialIndex": 1,
        "docType": 1
}