###
GET  http://localhost:3000/documents/get-setting-doc-by-type/1
content-type: application/json

###
GET  https://api.bigdatacloud.net/data/client-info
content-type: application/json


###
PATCH   http://localhost:3000/documents/update-setting-doc-by-type/1
content-type: application/json

{
        "initialIndex": 1,
        "docType": 1
}

###
POST http://localhost:3000/documents/generate-multiple
Content-Type: application/json

{
  "userId": "bLLbGN2fjvXe1wOuRe3cclYxx6l1"
}